import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/providers/theme";
import { SolanaWalletProvider } from "@/providers/solana";
import "./globals.css";

dayjs.extend(relativeTime);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SolanaWalletProvider>{children}</SolanaWalletProvider>
        </ThemeProvider>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}
